#!/bin/bash
echo"list of available strings"
environ
pause
echo "hit the enter key to continue"
clr 
echo"current directory is :\n"
pwd 
pause
echo "hit the enter key to continue"
echo"Directory that bash was excuted from is:"
cd $(dirname $(reallink -f $0))
pause
echo "hit the enter key to continue"
echo"testing cd functionality PWD should be set to the end of the current directory"
cd ~/home
pause
echo "testing the dir functinolity"
dir ~/home
echo "hit the enter key to continue"
help
clr
echo"testing is done"
pause
echo "hit the enter key to continue"
quit


